### ISSUE TITLE
NPE before Oreon death

### ISSUE THREAD

**Issue by Naman-sopho** [Terasology/MasterOfOreon#14]
The following NPE occurs just before the Oreon entity is destroyed. This might be caused due to the `DeathTimeComponent`'s "custom" constructor.
```
[main] INFO  o.t.logic.behavior.core.ActionNode - Exception while running action org.terasology.taskSystem.actions.NeedsFoodNode@688fb13b from entity EntityRef{id = 565, netId = 0, prefab = 'Oreons:OreonBuilder'}: 
java.lang.NullPointerException: null
	at org.terasology.reflection.metadata.ClassMetadata.copy(ClassMetadata.java:174)
	at org.terasology.reflection.metadata.AbstractClassLibrary.copy(AbstractClassLibrary.java:124)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:69)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:488)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:618)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:461)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:167)
	at org.terasology.deathSystem.DeathSystem.destroyOreon(DeathSystem.java:77)
	at org.terasology.healthSystem.OreonHealthSystem.checkOreonHealth(OreonHealthSystem.java:101)
	at org.terasology.healthSystem.OreonHealthSystem.reduceHealth(OreonHealthSystem.java:89)
	at org.terasology.taskSystem.actions.NeedsFoodNode.modify(NeedsFoodNode.java:93)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:78)
	at org.terasology.logic.behavior.core.SelectorNode.execute(SelectorNode.java:52)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:78)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.SelectorNode.execute(SelectorNode.java:52)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.SelectorNode.execute(SelectorNode.java:52)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.DecoratorNode.runChild(DecoratorNode.java:76)
	at org.terasology.logic.behavior.core.DecoratorNode.execute(DecoratorNode.java:89)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.DynamicSelectorNode.execute(DynamicSelectorNode.java:54)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner.step(DefaultBehaviorTreeRunner.java:84)
	at org.terasology.logic.behavior.Interpreter.tick(Interpreter.java:62)
	at org.terasology.logic.behavior.BehaviorSystem.update(BehaviorSystem.java:105)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
```

**Comment by Cervator** [comment]
Oh yep that's totally it. Should be able to just remove the constructor, update any code creating the component to just set the value directly, thus restoring the default no-arg constructor, and this will go away.
